# Generated by Django 3.0.7 on 2020-06-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sep_url', models.URLField()),
                ('pub_date', models.DateField(null=True)),
                ('rev_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edge_head', to='graph.Node')),
                ('tail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edge_tail', to='graph.Node')),
            ],
        ),
    ]
