# Generated by Django 3.0.7 on 2020-06-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sep_url', models.URLField()),
                ('pub_date', models.DateField(null=True)),
                ('rev_date', models.DateField(null=True)),
            ],
        ),
    ]
