# Generated by Django 3.0.7 on 2020-06-24 17:46
# Migrate NODES only from database
from django.db import migrations
import os
import pandas as pd

from graph.utils.network import Network

GRAPH_JSON_PATH = '../utils/related.jl'
RELATED_NODE_KEY = 'related'

def init_network(path):
    dirname = os.path.dirname(__file__)
    filename = os.path.join(dirname, GRAPH_JSON_PATH)
    return Network.from_jl(filename, RELATED_NODE_KEY).df

def reformat_dates(df):
    # df[df['pub_date'].isnull()] = None
    # df[df['rev_date'].isnull()] = None
    df['pub_date'] = pd.to_datetime(df['pub_date']).astype(str).astype(object)
    df['pub_date'][df['pub_date'] == 'NaT'] = None
    df['rev_date'] = pd.to_datetime(df['rev_date']).astype(str).astype(object)
    df['rev_date'][df['rev_date'] == 'NaT'] = None
    return df

def migrate_nodes_from_file(apps, schema_editor):
    df = init_network(GRAPH_JSON_PATH)
    df = reformat_dates(df)
    Node = apps.get_model('graph', 'Node')
    Node.objects.bulk_create([
        Node(
            name=r[1]['node'],
            title=r[1]['title'],
            sep_url=r[1]['url'],
            pub_date=r[1]['pub_date'],
            rev_date=r[1]['rev_date'],
        )
        for r in df.iterrows()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_nodes_from_file),
    ]
